/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lemon VPast
 */
public class ConvertFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form ConvertFrame
     */
    public ConvertFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hexa_entry = new javax.swing.JTextField();
        decimal_entry = new javax.swing.JTextField();
        binary_entry = new javax.swing.JTextField();
        convert_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        help_label = new javax.swing.JLabel();
        reset_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Hexadecimal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 70, 30);

        jLabel2.setText("Decimal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 60, 30);

        jLabel3.setText("Binary");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 200, 30, 30);
        getContentPane().add(hexa_entry);
        hexa_entry.setBounds(100, 50, 110, 30);
        getContentPane().add(decimal_entry);
        decimal_entry.setBounds(100, 130, 110, 30);
        getContentPane().add(binary_entry);
        binary_entry.setBounds(100, 200, 110, 30);

        convert_button.setText("Convert");
        convert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(convert_button);
        convert_button.setBounds(253, 130, 100, 23);

        jLabel4.setText("Hexa-Decimal-Binary conversion");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 90, 190, 14);

        help_label.setText("Either too many inputted or none");
        help_label.setEnabled(false);
        getContentPane().add(help_label);
        help_label.setBounds(230, 190, 200, 14);

        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_button);
        reset_button.setBounds(253, 160, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_buttonActionPerformed
        String hexa_entry_text = hexa_entry.getText();
        String decimal_entry_text = decimal_entry.getText();
        String binary_entry_text = binary_entry.getText();
        
        String logic = ConvertLogic.logic(hexa_entry_text, decimal_entry_text, binary_entry_text);
        switch(logic){
            case "binary":  decimal_entry.setText(String.valueOf((ConvertLogic.binaryToDec(binary_entry_text))));
                            hexa_entry.setText(ConvertLogic.hexaFromDec(Integer.parseInt(decimal_entry.getText())));
                            break;
            case "decimal": hexa_entry.setText(ConvertLogic.hexaFromDec(Integer.parseInt(decimal_entry_text)));
                            binary_entry.setText(String.valueOf(ConvertLogic.decToBinary(Integer.parseInt(decimal_entry_text))));
                            break;
            case "hexa":    binary_entry.setText(ConvertLogic.decToBinary(ConvertLogic.hexaToDec(hexa_entry_text)));
                            decimal_entry.setText(String.valueOf(ConvertLogic.hexaToDec(hexa_entry_text)));
                            break;
            default:        help_label.setEnabled(true);
                            break;
        }            
    }//GEN-LAST:event_convert_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        hexa_entry.setText("");
        decimal_entry.setText("");
        binary_entry.setText("");
    }//GEN-LAST:event_reset_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binary_entry;
    private javax.swing.JButton convert_button;
    private javax.swing.JTextField decimal_entry;
    private javax.swing.JLabel help_label;
    private javax.swing.JTextField hexa_entry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton reset_button;
    // End of variables declaration//GEN-END:variables
}
